background {
    monitor =
    path = /home/cnek/Pictures/coffee.jpg
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgb(ca9ee6)
    inner_color = rgb(303446)
    font_color = rgb(c6d0f5)
    placeholder_text = <i>Password...</i>
    position = 0, -100
    halign = center
    valign = center
}
